---
title: "Untitled"
author: "Leila Yan"
date: "2024-10-23"
output: html_document
---
```{r}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  dig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal()+theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot.continuous.fill = "viridis"
)
```

## do something simple
```{r}
x_vec = rnorm(30, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
```

I want a function to compute z-scores
```{r}
z_scores = function(x) {
  if(!is.numeric(x)) {
    stop("input must be numeric")
  }
  
  if(length(x) < 3){
    stop("input must have at least three numbers")
  }
  z = (x - mean(x)) / sd(x)
  
  return(z)
  
}

z_scores(x_vec)
```
Try my function on some other things, these should give errors
```{r, error=TRUE}
z_scores(3)
z_scores("my name is jeff") # can't take the mean of a character
z_scores(mtcars) # can't take the mean of a dataset
z_scores(c(TRUE, TRUE, FALSE, TRUE))
```

## multiple outputs

```{r}
mean_and_sd = function(x) {
  if(!is.numeric(x)) {
    stop("input must be numeric")
  }
  
  if(length(x) < 3){
    stop("input must have at least three numbers")
  }
  z = (x - mean(x)) / sd(x)
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(   #make this a dataframe
    mean = mean_x,
    sd = sd_x
  )

}

```

check that the function works
```{r}
x_vec = rnorm(100, mean = 3, sd = 4)
mean_and_sd(x_vec)
```

## multiple inputs
```{r}
#create a dataframe
sim_data = 
  tibble(
    x=rnorm(n=100, mean = 4, sd = 3)
  )

# compute mean, sd
sim_data %>%
  summarize(
    mean = mean(x),
    sd= sd(x)
  )
```

```{r}
sim_mean_sd = function(sample_size, mu=3, sigma=4) {
  
  sim_data = 
  tibble(
    x=rnorm(n=sample_size, mean = mu, sd = sigma)
  )

# compute mean, sd
  sim_data %>%
    summarize(
      mean = mean(x),
      sd= sd(x)
    )
  
}

sim_mean_sd(100, 6, 3) #100 is sample size

```

## An example copied from the p8105 website
```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

data_marj = 
  nsduh_html |> 
  html_table() |> 
  nth(1) |>
  slice(-1) |> 
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)) |>
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
```


```{r}
nsduh_table <- function(html, table_num, table_name) {
  
  table = 
    html |> 
    html_table() |> 
    nth(table_num) |>
    slice(-1) |> 
    select(-contains("P Value")) |>
    pivot_longer(
      -State,
      names_to = "age_year", 
      values_to = "percent") |>
    separate(age_year, into = c("age", "year"), sep = "\\(") |>
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent),
      name = table_name) |>
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
  
  table
  
}
```

```{r}

dynamite_urls = str_c(dynamite_url_base, 1:50)

nsduh_results = 
  bind_rows(
    nsduh_table(nsduh_html, 1, "marj_one_year"),
    nsduh_table(nsduh_html, 4, "cocaine_one_year"),
    nsduh_table(nsduh_html, 5, "heroin_one_year")
  )
```

## mean scoping example
```{r}
f = function(x) {
  z = x+y
  z
}

x =1
y=2

f(x=y)
# the reason we got 4 is because f is a function of x, argument name is x, take 2 and plug it into the function

```

## Fucntions as arguments

```{r}
my_summary = function(x, summ_func) {
  
  summ_func(x)
}

x_vec = rnorm(100, 3, 7)

mean(x_vec)
median(x_vec)

my_summary(x_vec, mean)
# can also be median, IQR
```




